import tkinter as tk
root = tk.Tk()
root.title("更新日志")
root.geometry("400x200")
label1 = tk.Label(root, text="1.2.3.0更新日志：")
label1.pack()
label2 = tk.Label(root, text="1.将窗口大小设置为300x200")
label2.pack()
label3 = tk.Label(root, text="2.增加了打开更新日志的按钮")
label3.pack()
label4 = tk.Label(root, text="3.增加了关闭窗口的按钮")
label4.pack()
label5 = tk.Label(root, text="4.增加了展示答案的按钮")
label5.pack()
root.mainloop()
